### PR TITLE
Update `libloading` to 0.8

### PR DESCRIPTION
**Pull request by ids1024**

### CODE REVIEW

**Comment by elinorbgr** [comment]
Given this would bump the MSRV, this would technically be a breaking change. But the changes in libloading for 0.8 don't have any consequence on dlib, so I'd be inclined to set the dependency as `libloading = ">= 0.7, < 0.9`.

However I'm not sure if that might technically still be a breaking change?

**Comment by daxpedda** [comment]
I would argue that in the strictest sense it is a breaking change, anybody doing `cargo update` or initializing the dependency from scratch would get the newer `libloading` version.

But it depends on your MSRV policy of course.

**Comment by elinorbgr** [comment]
My question is rather whether in practice it could cause trouble or not.

Though I think I'm going to decide that, if you need a rustc version as old as < 1.48, surely you can go through the trouble of setting explicitly the dependency on libloading to 0.7 in your cargo.toml.

**Comment by elinorbgr** [comment]
Done in bc1466a4f03b84bce955630eb1a0c6e3e532f2c4

**Pull request closed without merging**
