### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by alfiedotwtf**

### CODE REVIEW

**Comment by vberger** [comment]
Hi, thanks for the spell-checking. :slightly_smiling_face: 

The README of this repo is generated form the crate-level docs using cargo-readme, could you make sure to update it as well in your PR?

**Comment by alfiedotwtf** [comment]
Ah, sorry I missed that. Sure, I'll either do it tonight or over the weekend :)

**Comment by alfiedotwtf** [comment]
Maybe I'm missing something? I just did the following:

```
cargo readme > README.md
```

But there doesn't seem to be any change. Also, the typo wasn't in the README so I guess that explains the NOP :)

**Comment by vberger** [comment]
Ah yes, my bad, I thought this was a fix in the crate-level docs. My bad!

**Comment by alfiedotwtf** [comment]
Awesome, thanks :)

**Pull request merged**
